
# Jekyll configuration file
title: "Ktor 1.0.0"
description: Asynchronous framework for web applications
url: "https://api.ktor.io/"
baseurl: /1.0.0/

# Dirs
source: .
destination: ../1.0.0

ktor_version: 1.0.0

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - package-list
#include:
#  - package-list
